services:
  blue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ENVIRONMENT=blue
      - DEPLOYMENT_TIME=${DEPLOY_TIME}

  green:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      - ENVIRONMENT=green
      - DEPLOYMENT_TIME=${DEPLOY_TIME}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blue
      - green