services:
  blue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
    environment:
      - ENVIRONMENT=blue
      - DEPLOYMENT_TIME=${DEPLOY_TIME}
    networks:
      - deploy-net
      
  green:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
    environment:
      - ENVIRONMENT=green
      - DEPLOYMENT_TIME=${DEPLOY_TIME}
    networks:
      - deploy-net


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blue
      - green
    networks:
      - deploy-net

networks:
  deploy-net:
    driver: bridge
